# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gfBXNRu7ADupPXQxMGcGcXH-icm__Zc
"""

def operaciones_conjuntos():
    print("Creado por Miguel Acosta - Estudiante UNAB Ing Sistemas")
    print("Asistente de operaciones con conjuntos a su servicio.")


    print("Ingrese los elementos del conjunto universal (U), separados por comas uno por uno:")
    elementos_u = input().split(',')
    U = set(elementos_u)

    print("Ingrese los elementos del conjunto A, separados por comas uno por uno :")
    elementos_a = input().split(',')
    A = set(elementos_a)

    if not A.issubset(U):
        print("Error: El conjunto A no es subconjunto del conjunto universal U. intenta con otra combinacion")
        return

    operacion1 = (U.intersection(A)).union(A)
    operacion2 = U.difference(A.intersection(A))
    operacion3 = U.symmetric_difference(A).difference(A)

    print("Resultados:")
    print("(U⋂A)⋃A =", operacion1)
    print("U − A ⋂A =", operacion2)
    print("U⨁A − A =", operacion3)

operaciones_conjuntos()