# -*- coding: utf-8 -*-
"""TALLER 21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196HBR-qEeiHdNaNCFqZX3wyAKcp9C5Gm
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

# Datos de la tabla
x = np.array([0, 2, 4, 6, 8, 10, 12])
y = np.array([7.5, 1.8, -1.0, -1.8, -1.2, 2.2, 7.2])

# Ajuste de polinomio de segundo grado
coeficientes = np.polyfit(x, y, 2)
polinomio = np.poly1d(coeficientes)

# Valores predichos
y_pred = polinomio(x)

# Coeficiente de determinación (R^2)
r2 = r2_score(y, y_pred)

# Coeficiente de correlación (r)
correlacion = np.corrcoef(y, y_pred)[0, 1]

# Mostrar resultados
print("Coeficientes del polinomio (a*x^2 + b*x + c):")
print(coeficientes)
print(f"\nCoeficiente de determinación (R^2): {r2:.4f}")
print(f"Coeficiente de correlación (r): {correlacion:.4f}")

# Graficar
x_vals = np.linspace(min(x), max(x), 100)
y_vals = polinomio(x_vals)

plt.scatter(x, y, color='red', label='Datos')
plt.plot(x_vals, y_vals, color='blue', label='Ajuste cuadrático')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Ajuste de Polinomio de Segundo Grado')
plt.legend()
plt.grid(True)
plt.show()