# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9e4B7Xdr8IwaAaE6J6Jp3SEKIKZ0aht
"""

import numpy as np

n = int(input("Ingrese la longitud de los vectores: "))
vector_a = np.random.randint(1, 10, n)
vector_b = np.random.randint(1, 10, n)

print(f"\nVector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Producto escalar: {np.dot(vector_a, vector_b)}")

import numpy as np

operacion = input("Seleccione operación (suma o multiplicación): ").strip().lower()

filas_a, columnas_a = np.random.randint(2, 9, 2)
filas_b, columnas_b = (filas_a, columnas_a) if operacion == "suma" else (columnas_a, np.random.randint(2, 9))

matriz_a = np.random.randint(1, 10, (filas_a, columnas_a))
matriz_b = np.random.randint(1, 10, (filas_b, columnas_b))
resultado = matriz_a + matriz_b if operacion == "suma" else matriz_a @ matriz_b

print(f"\nMatriz A:\n{matriz_a}")
print(f"\nMatriz B:\n{matriz_b}")
print(f"\nResultado:\n{resultado}")