# -*- coding: utf-8 -*-
"""TALLER10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnWy3p-aLVQuEZ5X0Un9X2L1Mt9QgZNE
"""

import sympy as sp

def taylor_series(f, x0, x, order=3):
    return sum((f.diff(x, n).subs(x, x0) / sp.factorial(n)) * (x - x0) ** n for n in range(order + 1))


x = sp.Symbol('x')


f1 = 0.3*x**3 - 1.8*x**2 + 2.5*x - 1
x0_1 = 0.4
taylor_f1 = taylor_series(f1, x0_1, x)


approx_f1 = taylor_f1.subs(x, 0.5)
print(f"Aproximación de f(0.5): {approx_f1.evalf()}")


f2 = 1.4*sp.exp(x) - 3.2*x + 2.4
x0_2 = 0.6
taylor_f2 = taylor_series(f2, x0_2, x)


approx_f2 = taylor_f2.subs(x, 0.65)
print(f"Aproximación de f(0.65): {approx_f2.evalf()}")