# -*- coding: utf-8 -*-
"""TALLER6_miguel acosta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPMZCtpkeRp748jliu3u72VYUVDJzY7T
"""

import math

def calcular_coseno_serie_taylor(x, epsilon_s):

    x = float(x)


    coseno_aproximado = 1.0
    termino = 1.0
    n = 1
    factorial = 1
    signo = -1
    iteraciones = 0

    while True:

        termino = (x**(2*n)) / math.factorial(2*n)
        termino *= signo


        coseno_aproximado += termino


        if n > 0:
            epsilon_a = abs(termino / coseno_aproximado) * 100


        n += 1
        signo *= -1
        iteraciones += 1


        if epsilon_a < epsilon_s:
            break

    return coseno_aproximado, epsilon_a, iteraciones


x = float(input("Introduzca el valor en radianes (x): "))
epsilon_s = float(input("Introduzca el criterio de error esperado (εs): "))


coseno_estimado, epsilon_a, num_iteraciones = calcular_coseno_serie_taylor(x, epsilon_s)


print(f"Valor estimado del coseno: {coseno_estimado:.8f}")
print(f"Error aproximado relativo porcentual: {epsilon_a:.8f}%")
print(f"Número de iteraciones realizadas: {num_iteraciones}")