# -*- coding: utf-8 -*-
"""TALLER5_p1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJZkHqqG9-tOfL1rfSKOg3iLhf4wwyCe
"""

import math

def combinaciones(n, k):
    return math.comb(n, k)


total_aplicaciones = 20
seleccionadas = 8
formas_parte_a = combinaciones(total_aplicaciones, seleccionadas)


redes_sociales = 6
redes_seleccionadas = 3
resto_aplicaciones = 14
resto_seleccionadas = 5
formas_parte_b = combinaciones(redes_sociales, redes_seleccionadas) * combinaciones(resto_aplicaciones, resto_seleccionadas)


print(f"Parte a) Hay {formas_parte_a} formas de seleccionar 8 aplicaciones de 20.")
print(f"Parte b) Hay {formas_parte_b} formas de seleccionar 3 de las 6 redes sociales y 5 de las 14 aplicaciones restantes.")