# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RII11HVev2ARMZwkNc0_U_UTIssr3x6-
"""

from math import factorial
from itertools import permutations

def ejercisio_1():
  colores = 3
  lineas = 5
  transmision = 3
  cilindraje = 2
  total_1a = colores * lineas * transmision * cilindraje
  colores_nuevos = 10
  total_1b = colores_nuevos * lineas * transmision * cilindraje
  return total_1a, total_1b

def ejercisio_2():
    letras =26
    numeros = 10
    total_2a = (letras ** 3) * (numeros ** 3)
    total_2b = (factorial (letras) // factorial (letras - 3)) * (factorial (numeros) // factorial (numeros - 3))
    return total_2a, total_2b

def ejercisio_3():
      total_3 = factorial(10) // factorial(10 - 4)
      return total_3
def ejercisio_4():
        total_4 = 2 ** 12
        return total_4
def ejercisio_5():
          total_5a = factorial(9)
          total_5b = factorial(5)*factorial(5)
          total_5c = factorial(5)*factorial(4)
          return total_5a, total_5b,total_5c

if __name__ == "__main__":
    print("ejercisio 1:", ejercisio_1())
    print("ejercisio 2:", ejercisio_2())
    print("ejercisio 3:", ejercisio_3())
    print("ejercisio 4:", ejercisio_4())
    print("ejercisio 5:", ejercisio_5())