# -*- coding: utf-8 -*-
"""TALLER5_p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsHLEOezc2XWyGGSaZB8V3StwSXS0Iwh
"""

from math import comb

def manos_poker():
    total_cartas = 52
    cartas_mano = 5
    formas = comb(total_cartas, cartas_mano)
    print(f"a) Existen {formas} manos de póquer de 5 cartas seleccionadas de una baraja común de 52 cartas.")

def manos_mismo_palo():
    cartas_palo = 13
    cartas_mano = 5
    formas_por_palo = comb(cartas_palo, cartas_mano)
    total_formas = formas_por_palo * 4
    print(f"b) Existen {total_formas} manos de póquer donde todas las cartas son del mismo palo.")

def manos_full_house():
    trio = comb(13, 1) * comb(4, 3)
    pareja = comb(12, 1) * comb(4, 2)
    total_formas = trio * pareja
    print(f"c) Existen {total_formas} manos de póquer que contienen tres cartas de una denominación y dos de otra.")

def resolver_problemas():
    while True:
        print("\nElige un problema para resolver:")
        print("1. Manos de póquer (todas)")
        print("2. Manos de póquer con todas las cartas del mismo palo")
        print("3. Manos de póquer con un full house")
        print("4. Salir")

        opcion = input("Ingresa el número de la opción: ")

        if opcion == '1':
            manos_poker()
        elif opcion == '2':
            manos_mismo_palo()
        elif opcion == '3':
            manos_full_house()
        elif opcion == '4':
            print("Gracias por usar el programa. ¡Hasta luego!")
            break
        else:
            print("Opción no válida. Intenta de nuevo.")

        continuar = input("¿Quieres resolver otro problema? (sí/no): ").lower()
        if continuar != 'sí':
            print("Gracias por usar el programa. ¡Hasta luego!")
            break

resolver_problemas()