# -*- coding: utf-8 -*-
"""TALLER23

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XA-d1JmMWhOEXRe-e7_1-tO9yV36KMQm
"""

from scipy.interpolate import lagrange
import numpy as np

# Datos base
x_vals = np.array([1, 3, 5, 7, 9])
y_vals = np.array([3, 0, -1, 2.5, 1])

# Punto a estimar
x_eval = 4.25

# Función para imprimir resultados por grado
def interpolar_y_estimar(grado):
    x_sub = x_vals[1:1+grado+1]  # Tomamos los puntos más cercanos a 4.25
    y_sub = y_vals[1:1+grado+1]

    poly = lagrange(x_sub, y_sub)
    estimacion = poly(x_eval)

    print(f"Grado {grado}:")
    print(f"Polinomio: {poly}")
    print(f"f({x_eval}) ≈ {estimacion}\n")

# Interpolaciones de grado 1, 2 y 3
for grado in range(1, 4):
    interpolar_y_estimar(grado)