# -*- coding: utf-8 -*-
"""TALLER12MC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0ajN_6ODbCfYq_5XP6VlH6EQl5uCaOF
"""

import numpy as np

def error_propagation(f, df, x_val, dx):
    df_val = df(x_val)
    error_f = abs(df_val) * dx
    return error_f


def f1(x):
    return 1.1*x**4 - 1.9*x**3 + 1.2*x**2 - 2*x + 4

def df1(x):
    return 4.4*x**3 - 5.7*x**2 + 2.4*x - 2

x1 = 1.4
dx1 = 0.05
error_f1 = error_propagation(f1, df1, x1, dx1)
print(f"Error en f1(x) para x={x1}: {error_f1}")


def f2(x):
    return np.cos(x) * np.log(2*x)

def df2(x):
    return -np.sin(x) * np.log(2*x) + (np.cos(x) / x)

x2 = np.pi / 3
dx2 = 0.005
error_f2 = error_propagation(f2, df2, x2, dx2)
print(f"Error en f2(x) para x={x2}: {error_f2}")