# -*- coding: utf-8 -*-
"""Taller19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10H3UFerrxoPkYPPI-kDCX3Se42h4w_pu
"""

import numpy as np
import matplotlib.pyplot as plt


x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([1.5, 2.5, 3.5, 4.5, 6.5, 9])


ln_y = np.log(y)


n = len(x)
pendiente = (n * np.sum(x * ln_y) - np.sum(x) * np.sum(ln_y)) / (n * np.sum(x**2) - np.sum(x)**2)
intercepto_ln = (np.sum(ln_y) - pendiente * np.sum(x)) / n
a = np.exp(intercepto_ln)


def modelo(x): return a * np.exp(pendiente * x)


print(f"Modelo: y = {a:.4f} * e^({pendiente:.4f}x)")


x_vals = np.linspace(1, 6, 100)
plt.plot(x_vals, modelo(x_vals), color='red', label='Modelo ajustado')
plt.scatter(x, y, color='blue', label='Datos')
plt.title("Regresión Exponencial")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid()
plt.show()